# Generated by Django 4.0.3 on 2022-03-28 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInformation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Company_Name', models.CharField(blank=True, max_length=500, null=True)),
                ('Company_Address', models.CharField(blank=True, max_length=1000, null=True)),
                ('Company_Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('Company_Phone', models.CharField(blank=True, max_length=50, null=True)),
                ('Company_Fax', models.CharField(blank=True, max_length=50, null=True)),
                ('Company_Web_site', models.CharField(blank=True, max_length=50, null=True)),
                ('Company_Short_Name', models.CharField(blank=True, max_length=50, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('issu_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Edits', models.CharField(blank=True, max_length=10, null=True)),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
