# Generated by Django 4.0.3 on 2022-03-28 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0005_remove_companyinformation_issu_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CashReceive',
            new_name='CashReceiveList',
        ),
        migrations.RenameModel(
            old_name='ExpenseName',
            new_name='ExpenseList',
        ),
    ]
