# Generated by Django 4.0.3 on 2022-03-29 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0006_rename_cashreceive_cashreceivelist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashreceiveentry',
            name='To_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expenseentry',
            name='To_Date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
